# Generated by Django 3.1.6 on 2021-04-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0002_auto_20210428_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdemographic',
            name='PatientID',
            field=models.TextField(blank=True, unique=True),
        ),
    ]
