# Generated by Django 3.1.6 on 2021-04-27 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlwaysRegex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pattern', models.TextField(unique=True)),
                ('Annotation', models.CharField(choices=[('Y', 'Always Yes'), ('N', 'Always No'), ('T', 'Always Neither')], max_length=1)),
                ('CreatedBy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PatientID', models.IntegerField(blank=True, null=True)),
                ('PatientEncounterID', models.CharField(blank=True, max_length=100, null=True)),
                ('NoteID', models.IntegerField(blank=True, null=True, unique=True)),
                ('Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PatientDemographic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PatientID', models.IntegerField(blank=True, unique=True)),
                ('MRN', models.TextField(blank=True, null=True)),
                ('EMPI', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SeedRegex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pattern', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contents', models.TextField()),
                ('Note', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gui.note')),
            ],
        ),
        migrations.CreateModel(
            name='SentenceSeedRegex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SeedRegex', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gui.seedregex')),
                ('Sentence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gui.sentence')),
            ],
        ),
        migrations.CreateModel(
            name='SentenceAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompletedAt', models.DateTimeField(null=True)),
                ('Sentence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gui.sentence')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SentenceAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Label', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('NTR', 'Neither')], max_length=3)),
                ('Annotator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('Sentence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gui.sentence')),
            ],
        ),
        migrations.CreateModel(
            name='SentenceAlwaysRegex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AlwaysRegex', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gui.alwaysregex')),
                ('Sentence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gui.sentence')),
            ],
        ),
    ]
