# Generated by Django 3.1.6 on 2021-04-28 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sentenceassignment',
            constraint=models.UniqueConstraint(fields=('User', 'Sentence'), name='uq_assignment'),
        ),
    ]
