# Generated by Django 3.1.6 on 2021-04-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0003_auto_20210428_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='NoteID',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='PatientID',
            field=models.TextField(blank=True, null=True),
        ),
    ]
